name: MasterThesis

dependencies:
- python=3.7.*
- numpy=1.18.*
- pandas=1.0.* 
- jupyter=1.0.*
- matplotlib=3.2.*
- seaborn=0.10.*
- statsmodels=0.11.*
- scipy=1.5.*
- patsy=0.5.*
- xlrd=1.2.*
- pip=20.0.*
- pip:
  - tabulate